
---

name: 'Bundle Release'

on:
  release:
    types: [published, edited]

jobs:
  deploy_to_server:
    name: "Deploying Containers"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Read Published Tag"
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"

      - name: "Install Packages"
        run: npm ci

      - name: "Compile Assets"
        run: npm run build:prod

      - name: "Zip Archive"
        uses: papeloto/action-zip@v1
        with:
          files: ./dist
          dest: result.zip

      - name: "Upload binaries to release"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: result.zip
          asset_name: ${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip
          tag: ${{ github.ref }}
